export type SortableColumn =
    | "name"
    | "email"
    | "status"
    | "role"
    | "course"
    | "description"
    | "startDate"
    | "endDate"
    | "student"
    | "activity"
    | "deadline"
    | "submitted"
    | "late"
    | "review"
    | "reviewed";
